version: '3.8'

services:
  website:
    build: 
      context: ./websites
      dockerfile: Dockerfile
    container_name: cloud-resume-web
    ports:
      - "8080:80"
    volumes:
      - ./websites:/usr/share/nginx/html
    restart: always
